/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import gsap from 'gsap';
import { useThree } from '@react-three/fiber';


export function BlueAvatar(props) {

    const [material, setMaterial] = useState()
    const { camera } = useThree()

    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/KhaledSaiedPortfolio/untitled.glb')
    const { actions } = useAnimations(animations, group)

    useEffect(() => {
        gsap.to(camera.position, { z: 1.8, duration: 3, ease: 'power2.inOut' })

    }, [])

    return (
        <>
            <meshBasicMaterial color="blue" ref={setMaterial} opacity={0.4} transparent={true} />

            <group ref={group} {...props} dispose={null}>
                <group name="Scene">
                    <group name="Main-Human" rotation={[Math.PI / 2, 0, 0]}>
                        <skinnedMesh
                            name="EyeLeft_Wolf3D_Eye"
                            geometry={nodes.EyeLeft_Wolf3D_Eye.geometry}
                            material={material}
                            skeleton={nodes.EyeLeft_Wolf3D_Eye.skeleton}
                        />
                        <skinnedMesh
                            name="EyeRight_Wolf3D_Eye"
                            geometry={nodes.EyeRight_Wolf3D_Eye.geometry}
                            material={material}
                            skeleton={nodes.EyeRight_Wolf3D_Eye.skeleton}
                        />
                        <skinnedMesh
                            name="Wolf3D_Body_Wolf3D_Body"
                            geometry={nodes.Wolf3D_Body_Wolf3D_Body.geometry}
                            material={material}
                            skeleton={nodes.Wolf3D_Body_Wolf3D_Body.skeleton}
                        />
                        <skinnedMesh
                            name="Wolf3D_Hair_Wolf3D_Hair"
                            geometry={nodes.Wolf3D_Hair_Wolf3D_Hair.geometry}
                            material={material}
                            skeleton={nodes.Wolf3D_Hair_Wolf3D_Hair.skeleton}
                        />
                        <skinnedMesh
                            name="Wolf3D_Head_Wolf3D_Skin"
                            geometry={nodes.Wolf3D_Head_Wolf3D_Skin.geometry}
                            material={material}
                            skeleton={nodes.Wolf3D_Head_Wolf3D_Skin.skeleton}
                        />
                        <skinnedMesh
                            name="Wolf3D_Outfit_Bottom_Wolf3D_Outfit_Bottom"
                            geometry={nodes.Wolf3D_Outfit_Bottom_Wolf3D_Outfit_Bottom.geometry}
                            material={material}
                            skeleton={nodes.Wolf3D_Outfit_Bottom_Wolf3D_Outfit_Bottom.skeleton}
                        />
                        <skinnedMesh
                            name="Wolf3D_Outfit_Footwear_Wolf3D_Outfit_Footwear"
                            geometry={nodes.Wolf3D_Outfit_Footwear_Wolf3D_Outfit_Footwear.geometry}
                            material={material}
                            skeleton={nodes.Wolf3D_Outfit_Footwear_Wolf3D_Outfit_Footwear.skeleton}
                        />
                        <skinnedMesh
                            name="Wolf3D_Outfit_Top_Wolf3D_Outfit_Top"
                            geometry={nodes.Wolf3D_Outfit_Top_Wolf3D_Outfit_Top.geometry}
                            material={material}
                            skeleton={nodes.Wolf3D_Outfit_Top_Wolf3D_Outfit_Top.skeleton}
                        />
                        <skinnedMesh
                            name="Wolf3D_Teeth_Wolf3D_Teeth"
                            geometry={nodes.Wolf3D_Teeth_Wolf3D_Teeth.geometry}
                            material={material}
                            skeleton={nodes.Wolf3D_Teeth_Wolf3D_Teeth.skeleton}
                        />
                        <primitive object={nodes.mixamorigHips} />
                    </group>
                    <group name="EyeLeft" position={[-1.788, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
                    <group name="EyeRight" position={[-1.788, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
                    <group name="Wolf3D_Head" position={[-1.788, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
                    <group name="Wolf3D_Teeth" position={[-1.788, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
                    <group name="Wolf3D_Hair" position={[-1.788, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
                    <group name="Wolf3D_Outfit_Top" position={[-1.788, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
                    <group
                        name="Wolf3D_Outfit_Bottom"
                        position={[-1.788, 0, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                    />
                    <group
                        name="Wolf3D_Outfit_Footwear"
                        position={[-1.788, 0, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                    />
                    <group name="Wolf3D_Body" position={[-1.788, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
                </group>
            </group>
        </>
    )
}

useGLTF.preload('/KhaledSaiedPortfolio/untitled.glb')
